export enum ResponseCodes {
  SUCCESS_REQUEST = 'OPERATION_SUCCESS',
  BAD_REQUEST = 'BAD_REQUEST',
  NOT_FOUND = 'NOT_FOUND',
  UNAUTHORIZED = 'UNAUTHORIZED_ERROR',
  PROCESS_ERROR = 'PROCESS_ERROR',
  UNCONTROLLER_ERROR = 'UNCONTROLLER_ERROR',
  UNAVAILABLE_SERVICE = 'UNAVAILABLE_SERVICE'
}
